import 'package:flutter/material.dart';

// ─────────────────────────────────────────────────────────────────────────────
// AgroGuard AI – Language Provider
// Global ValueNotifier + Translation Maps for 5 Indian languages + English
// ─────────────────────────────────────────────────────────────────────────────

class AppLang {
  AppLang._();

  /// Global language code – changing this rebuilds all ValueListenableBuilders
  static final ValueNotifier<String> current = ValueNotifier('en');

  static const List<Map<String, String>> languages = [
    {'code': 'en', 'name': 'English',  'native': 'English', 'flag': '🇬🇧'},
    {'code': 'hi', 'name': 'Hindi',    'native': 'हिन्दी',   'flag': '🇮🇳'},
    {'code': 'pa', 'name': 'Punjabi',  'native': 'ਪੰਜਾਬੀ',  'flag': '🇮🇳'},
    {'code': 'ta', 'name': 'Tamil',    'native': 'தமிழ்',   'flag': '🇮🇳'},
    {'code': 'bn', 'name': 'Bengali',  'native': 'বাংলা',   'flag': '🇧🇩'},
  ];
}

// ─────────────────────────────────────────────────────────────────────────────
// AppStrings – static translation lookup
// ─────────────────────────────────────────────────────────────────────────────

class AppStrings {
  AppStrings._();

  static String t(String key) =>
      (_strings[AppLang.current.value] ?? _strings['en']!)[key] ??
      (_strings['en']!)[key] ??
      key;

  static const Map<String, Map<String, String>> _strings = {
    // ── ENGLISH ──────────────────────────────────────────────────────────────
    'en': {
      'appName':          'AgroGuard AI',
      'appBarTitle':      'AgroGuard AI  |  CoderPirates',
      'byCoderPirates':   'by CoderPirates',
      'tagline':          'Nurturing Every Harvest with Intelligence',
      'motto':            'Protecting farms, empowering farmers',
      'aiPowered':        'AI Powered',
      'realTime':         'Real-Time',
      'organicTips':      'Organic Tips',
      'smartTools':       'Smart Tools',
      'features':         '5 Features',
      'cropAdvisor':      'Crop\nAdvisor',
      'cropAdvisorSub':   'AI-powered recommendations',
      'diseaseDetector':  'Disease\nDetector',
      'diseaseDetectorSub': 'Leaf image analysis',
      'fieldMonitor':     'Field\nMonitor',
      'fieldMonitorSub':  'Live sensor dashboard',
      'ecoGuardian':      'Eco\nGuardian',
      'ecoGuardianSub':   'Sustainability insights',
      'aboutTitle':       'About AgroGuard AI by CoderPirates',
      'about1':           'Machine learning crop recommendations based on soil & weather',
      'about2':           'Camera-based leaf disease detection with treatment plans',
      'about3':           'Real-time IoT sensor monitoring for field conditions',
      'about4':           'Organic & bio-control alternatives for sustainable farming',
      'version':          'AgroGuard AI by CoderPirates v1.0.0',
      'copyright':        '© 2025 CoderPirates',
      'selectLanguage':   'Select Language',
      'language':         'Language',
      // Government Portal
      'govtServices':     'Govt Services',
      'govtServicesSub':  'Mandi prices, schemes & advisories',
      'govtPortalTitle':  'Government Services',
      'govtPortalSubtitle': 'Access mandi prices, schemes, insurance & advisories',
      'govtPortalBadge':  'Government of India',
      'mandiPrices':      'Mandi Prices',
      'mandiPricesSub':   'Live crop prices from eNAM mandis',
      'govtSchemes':      'Govt Schemes',
      'govtSchemesSub':   'Check eligibility for 12+ schemes',
      'cropInsurance':    'Crop Insurance',
      'cropInsuranceSub': 'PMFBY premium calculator & claim tracker',
      'govtAdvisories':   'Govt Advisories',
      'govtAdvisoriesSub':'Weather, pest & crop management alerts',
      'govtDataNote':     'Data Source',
      'govtDataNoteDetail': 'Prices and advisories are based on government portal data patterns',
      'prices':           'Prices',
      'schemes':          'Schemes',
      'alerts':           'Alerts',
      'critical':         'Critical',
      'pricesAvailable':  'prices available',
      'schemesAvailable': 'schemes available',
      'liveprices':       'Live Prices',
      'marketAlerts':     'Market Alerts',
      'seasonalGuide':    'Seasonal Guide',
      'selectState':      'Select State',
      'selectCrop':       'Select Crop',
      'noData':           'No data available',
      'noAlerts':         'No alerts',
      'priceOverview':    'Price Overview',
      'avg':              'Avg',
      'highest':          'Highest',
      'lowest':           'Lowest',
      'aboveMSP':         'Above MSP',
      'belowMSP':         'Below MSP',
      'minPrice':         'Min',
      'modalPrice':       'Modal',
      'maxPrice':         'Max',
      'arrival':          'Arrival',
      'bestSell':         'Best Sell',
      'bestBuy':          'Best Buy',
      'schemeCheckerTitle':'Scheme Eligibility Checker',
      'schemeCheckerSub': 'Fill your profile to find matching government schemes',
      'yourAge':          'Your Age',
      'enterAge':         'Enter your age',
      'genderLabel':      'Gender',
      'male':             'Male',
      'female':           'Female',
      'stateLabel':       'State',
      'landHolding':      'Land Holding (Hectares)',
      'enterLand':        'Enter land in hectares',
      'farmerTypeLabel':  'Farmer Type',
      'allTypes':         'All Types',
      'smallMarginal':    'Small/Marginal',
      'mediumFarmer':     'Medium',
      'largeFarmer':      'Large',
      'interestKeywords': 'Interest Keywords (optional)',
      'enterKeywords':    'e.g., solar, loan, organic',
      'checkEligibility': 'Check Eligibility',
      'required':         'Required',
      'editProfile':      'Edit Profile',
      'youAreEligible':   'You are eligible for',
      'outOf':            'out of',
      'schemesWord':      'schemes',
      'eligibilityNote':  'Tap any scheme to see full details',
      'eligibleSchemes':  'Eligible Schemes',
      'notEligible':      'Not Eligible',
      'description':      'Description',
      'benefits':         'Benefits',
      'eligibilityReq':   'Eligibility',
      'documents':        'Documents Required',
      'howToApply':       'How to Apply',
      'visitGovtPortal':  'Visit Government Portal',
      'govtPortalLinks':  'Direct Portal Links',
      'errorOccurred':    'An error occurred',
      'calculator':       'Calculator',
      'claimStatus':      'Claim Status',
      'deadlines':        'Deadlines',
      'pmfbyCalc':        'PMFBY Premium Calculator',
      'pmfbyCalcSub':     'Calculate your crop insurance premium',
      'selectSeason':     'Select Season',
      'areaHectares':     'Area (Hectares)',
      'calculatePremium': 'Calculate Premium',
      'premiumBreakdown': 'Premium Breakdown',
      'crop':             'Crop',
      'season':           'Season',
      'area':             'Area',
      'hectares':         'hectares',
      'sumInsured':       'Sum Insured',
      'youPay':           'You Pay',
      'govtPays':         'Govt Pays',
      'govtSubsidy':      'Govt Subsidy',
      'enrollBy':         'Enroll By',
      'applicationId':    'Application ID',
      'check':            'Check',
      'premiumPaid':      'Premium Paid',
      'insurer':          'Insurer',
      'claimAmount':      'Claim Amount',
      'timeline':         'Timeline',
      'enrollStart':      'Enrollment Start',
      'enrollEnd':        'Enrollment End',
      'seasonPeriod':     'Season Period',
      'allCategories':    'All',
      'allStates':        'All States',
      'noAdvisories':     'No advisories found',
      // Crop Advisor
      'cropAdvisorTitle': 'Crop Advisor',
      'soilWeatherTitle': 'Enter Soil & Weather Data',
      'soilWeatherSub':   'Our AI analyzes your field conditions to recommend the optimal crop',
      'soilNutrients':    'Soil Nutrients',
      'weatherCond':      'Weather & Soil Conditions',
      'nitrogen':         'Nitrogen (N)',
      'phosphorus':       'Phosphorus (P)',
      'potassium':        'Potassium (K)',
      'temperature':      'Temperature',
      'humidity':         'Humidity',
      'phLevel':          'pH Level',
      'rainfall':         'Rainfall',
      'getRecommendation':'Get Recommendation',
      'analyzing':        'Analyzing...',
      'recommendedCrop':  'Recommended Crop',
      'confidence':       'Confidence: ',
      // Disease Detector
      'diseaseDetectorTitle': 'Disease Detector',
      'newAnalysis':      'New Analysis',
      'history':          'History',
      'uploadImage':      'Upload Leaf / Crop Image',
      'noImageSelected':  'No image selected',
      'takeOrChoose':     'Take a photo or choose from gallery',
      'gallery':          'Gallery',
      'camera':           'Camera',
      'analyseDisease':   'Analyse for Disease',
      'analysing':        'Analysing...',
      'analysisResults':  'Analysis Results',
      'saveHistory':      'Save to History',
      'notesTitle':       'Notes & Save',
      'notesHint':        'E.g. Field 3, south corner; 30% canopy affected…',
      'saveSuccess':      'Analysis saved successfully!',
      'noHistoryYet':     'No analyses saved yet',
      'noHistoryHint':    'Run an analysis and tap Save to History',
      'deleteAnalysis':   'Delete Analysis',
      'deleteConfirm':    'Remove this record permanently?',
      'cancel':           'Cancel',
      'delete':           'Delete',
      'symptoms':         'Symptoms',
      'cause':            'Cause',
      'treatment':        'Treatment',
      'prevention':       'Prevention',
      'organicOptions':   'Organic / Bio-control Options',
      'preventiveCare':   'Preventive Care',
      'matchedDB':        'Matched in local disease database',
      'noDBMatch':        'No local DB match – showing API data only',
      'totalAnalyses':    'Total',
      'avgConf':          'Avg Conf',
      'topDisease':       'Top Disease',
      // Sensor Dashboard
      'fieldMonitorTitle':'Field Monitor',
      'demoScenarios':    'Demo Scenarios',
      'demoScenariosSub': 'Switch between realistic crop scenarios',
      'sensorData':       'Real-Time Sensor Data',
      'sensorCount':      '9 Sensors',
      'smartRecs':        'Smart Recommendations',
      'activeAlerts':     'Active Alerts',
      'connecting':       'Connecting to sensors...',
      'statusOptimal':    'Optimal',
      'statusCaution':    'Caution',
      'statusAlert':      'Alert',
      'statusHealthy':    'Healthy',
      'statusFair':       'Fair',
      'statusPoor':       'Poor',
      'trendStable':      'Stable',
      'trendImproving':   'Improving',
      'trendDeclining':   'Declining',
    },

    // ── HINDI ─────────────────────────────────────────────────────────────────
    'hi': {
      'appName':          'एग्रोगार्ड AI',
      'appBarTitle':      'एग्रोगार्ड AI  |  CoderPirates',
      'byCoderPirates':   'CoderPirates द्वारा',
      'tagline':          'हर फसल को बुद्धिमत्ता से पोषित करना',
      'motto':            'खेतों की रक्षा, किसानों का सशक्तिकरण',
      'aiPowered':        'AI संचालित',
      'realTime':         'रियल-टाइम',
      'organicTips':      'जैविक टिप्स',
      'smartTools':       'स्मार्ट टूल्स',
      'features':         '5 विशेषताएं',
      'cropAdvisor':      'फसल\nसलाहकार',
      'cropAdvisorSub':   'AI आधारित सुझाव',
      'diseaseDetector':  'रोग\nपहचानकर्ता',
      'diseaseDetectorSub': 'पत्ती छवि विश्लेषण',
      'fieldMonitor':     'क्षेत्र\nमॉनिटर',
      'fieldMonitorSub':  'लाइव सेंसर डैशबोर्ड',
      'ecoGuardian':      'पर्यावरण\nरक्षक',
      'ecoGuardianSub':   'स्थायित्व अंतर्दृष्टि',
      'aboutTitle':       'AgroGuard AI के बारे में',
      'about1':           'मिट्टी और मौसम के आधार पर ML फसल सुझाव',
      'about2':           'कैमरे से पत्ती रोग की पहचान और उपचार',
      'about3':           'रियल-टाइम IoT सेंसर निगरानी',
      'about4':           'टिकाऊ खेती के लिए जैविक विकल्प',
      'version':          'एग्रोगार्ड AI - CoderPirates v1.0.0',
      'copyright':        '© 2025 CoderPirates',
      'selectLanguage':   'भाषा चुनें',
      'language':         'भाषा',
      // Government Portal
      'govtServices':     'सरकारी सेवाएं',
      'govtServicesSub':  'मंडी मूल्य, योजनाएं और सलाह',
      'govtPortalTitle':  'सरकारी सेवाएं',
      'govtPortalSubtitle': 'मंडी भाव, योजनाएं, बीमा और सलाह देखें',
      'govtPortalBadge':  'भारत सरकार',
      'mandiPrices':      'मंडी भाव',
      'mandiPricesSub':   'eNAM मंडियों से लाइव फसल भाव',
      'govtSchemes':      'सरकारी योजनाएं',
      'govtSchemesSub':   '12+ योजनाओं में पात्रता जांचें',
      'cropInsurance':    'फसल बीमा',
      'cropInsuranceSub': 'PMFBY प्रीमियम कैलकुलेटर और दावा ट्रैकर',
      'govtAdvisories':   'सरकारी सलाह',
      'govtAdvisoriesSub':'मौसम, कीट और फसल प्रबंधन अलर्ट',
      'govtDataNote':     'डेटा स्रोत',
      'govtDataNoteDetail':'कीमतें और सलाह सरकारी पोर्टल डेटा पर आधारित हैं',
      'prices':           'भाव',
      'schemes':          'योजनाएं',
      'alerts':           'अलर्ट',
      'critical':         'गंभीर',
      'pricesAvailable':  'भाव उपलब्ध',
      'schemesAvailable': 'योजनाएं उपलब्ध',
      'liveprices':       'लाइव भाव',
      'marketAlerts':     'बाजार अलर्ट',
      'seasonalGuide':    'मौसमी गाइड',
      'selectState':      'राज्य चुनें',
      'selectCrop':       'फसल चुनें',
      'noData':           'कोई डेटा नहीं',
      'noAlerts':         'कोई अलर्ट नहीं',
      'priceOverview':    'मूल्य अवलोकन',
      'avg':              'औसत',
      'highest':          'अधिकतम',
      'lowest':           'न्यूनतम',
      'aboveMSP':         'MSP से ऊपर',
      'belowMSP':         'MSP से नीचे',
      'minPrice':         'न्यूनतम',
      'modalPrice':       'मॉडल',
      'maxPrice':         'अधिकतम',
      'arrival':          'आवक',
      'bestSell':         'बेचने का सही समय',
      'bestBuy':          'खरीदने का सही समय',
      'schemeCheckerTitle':'योजना पात्रता जांच',
      'schemeCheckerSub': 'अपनी प्रोफाइल भरें और योजनाएं खोजें',
      'yourAge':          'आपकी आयु',
      'enterAge':         'आयु दर्ज करें',
      'genderLabel':      'लिंग',
      'male':             'पुरुष',
      'female':           'महिला',
      'stateLabel':       'राज्य',
      'landHolding':      'भूमि (हेक्टेयर)',
      'enterLand':        'हेक्टेयर में भूमि दर्ज करें',
      'farmerTypeLabel':  'किसान प्रकार',
      'allTypes':         'सभी प्रकार',
      'smallMarginal':    'लघु/सीमांत',
      'mediumFarmer':     'मध्यम',
      'largeFarmer':      'बड़ा',
      'interestKeywords': 'रुचि शब्द (वैकल्पिक)',
      'enterKeywords':    'जैसे, सोलर, लोन, जैविक',
      'checkEligibility': 'पात्रता जांचें',
      'required':         'आवश्यक',
      'editProfile':      'प्रोफाइल बदलें',
      'youAreEligible':   'आप पात्र हैं',
      'outOf':            'में से',
      'schemesWord':      'योजनाओं',
      'eligibilityNote':  'विवरण देखने के लिए किसी योजना पर टैप करें',
      'eligibleSchemes':  'पात्र योजनाएं',
      'notEligible':      'अपात्र',
      'description':      'विवरण',
      'benefits':         'लाभ',
      'eligibilityReq':   'पात्रता',
      'documents':        'आवश्यक दस्तावेज',
      'howToApply':       'कैसे आवेदन करें',
      'visitGovtPortal':  'सरकारी पोर्टल पर जाएं',
      'govtPortalLinks':  'सरकारी पोर्टल लिंक',
      'errorOccurred':    'त्रुटि हुई',
      'calculator':       'कैलकुलेटर',
      'claimStatus':      'दावा स्थिति',
      'deadlines':        'अंतिम तिथि',
      'pmfbyCalc':        'PMFBY प्रीमियम कैलकुलेटर',
      'pmfbyCalcSub':     'फसल बीमा प्रीमियम कैलकुलेट करें',
      'selectSeason':     'मौसम चुनें',
      'areaHectares':     'क्षेत्र (हेक्टेयर)',
      'calculatePremium': 'प्रीमियम कैलकुलेट करें',
      'premiumBreakdown': 'प्रीमियम विवरण',
      'crop':             'फसल',
      'season':           'मौसम',
      'area':             'क्षेत्र',
      'hectares':         'हेक्टेयर',
      'sumInsured':       'बीमित राशि',
      'youPay':           'आप भुगतान करें',
      'govtPays':         'सरकार भुगतान करे',
      'govtSubsidy':      'सरकारी सब्सिडी',
      'enrollBy':         'नामांकन तिथि',
      'applicationId':    'आवेदन आईडी',
      'check':            'जांचें',
      'premiumPaid':      'प्रीमियम भुगतान',
      'insurer':          'बीमाकर्ता',
      'claimAmount':      'दावा राशि',
      'timeline':         'समयरेखा',
      'enrollStart':      'नामांकन शुरू',
      'enrollEnd':        'नामांकन अंत',
      'seasonPeriod':     'मौसम अवधि',
      'allCategories':    'सभी',
      'allStates':        'सभी राज्य',
      'noAdvisories':     'कोई सलाह नहीं मिली',
      // Crop Advisor
      'cropAdvisorTitle': 'फसल सलाहकार',
      'soilWeatherTitle': 'मिट्टी और मौसम डेटा दर्ज करें',
      'soilWeatherSub':   'हमारा AI आपकी खेत की स्थिति का विश्लेषण करके सर्वोत्तम फसल की सिफारिश करता है',
      'soilNutrients':    'मिट्टी पोषक तत्व',
      'weatherCond':      'मौसम और मिट्टी की स्थिति',
      'nitrogen':         'नाइट्रोजन (N)',
      'phosphorus':       'फास्फोरस (P)',
      'potassium':        'पोटेशियम (K)',
      'temperature':      'तापमान',
      'humidity':         'आर्द्रता',
      'phLevel':          'pH स्तर',
      'rainfall':         'वर्षा',
      'getRecommendation':'सिफारिश प्राप्त करें',
      'analyzing':        'विश्लेषण हो रहा है...',
      'recommendedCrop':  'अनुशंसित फसल',
      'confidence':       'विश्वास: ',
      // Disease Detector
      'diseaseDetectorTitle': 'रोग पहचानकर्ता',
      'newAnalysis':      'नया विश्लेषण',
      'history':          'इतिहास',
      'uploadImage':      'पत्ती / फसल छवि अपलोड करें',
      'noImageSelected':  'कोई छवि नहीं चुनी',
      'takeOrChoose':     'फोटो लें या गैलरी से चुनें',
      'gallery':          'गैलरी',
      'camera':           'कैमरा',
      'analyseDisease':   'रोग के लिए विश्लेषण करें',
      'analysing':        'विश्लेषण हो रहा है...',
      'analysisResults':  'विश्लेषण परिणाम',
      'saveHistory':      'इतिहास में सहेजें',
      'notesTitle':       'नोट्स और सहेजें',
      'notesHint':        'जैसे क्षेत्र 3, दक्षिण कोना; 30% छत्र प्रभावित...',
      'saveSuccess':      'विश्लेषण सफलतापूर्वक सहेजा गया!',
      'noHistoryYet':     'अभी तक कोई विश्लेषण सहेजा नहीं',
      'noHistoryHint':    'विश्लेषण चलाएं और इतिहास में सहेजें पर टैप करें',
      'deleteAnalysis':   'विश्लेषण हटाएं',
      'deleteConfirm':    'इस रिकॉर्ड को स्थायी रूप से हटाएं?',
      'cancel':           'रद्द करें',
      'delete':           'हटाएं',
      'symptoms':         'लक्षण',
      'cause':            'कारण',
      'treatment':        'उपचार',
      'prevention':       'रोकथाम',
      'organicOptions':   'जैविक / जैव-नियंत्रण विकल्प',
      'preventiveCare':   'निवारक देखभाल',
      'matchedDB':        'स्थानीय रोग डेटाबेस में मिला',
      'noDBMatch':        'कोई स्थानीय DB मिलान नहीं – केवल API डेटा',
      'totalAnalyses':    'कुल',
      'avgConf':          'औसत',
      'topDisease':       'मुख्य रोग',
      // Sensor Dashboard
      'fieldMonitorTitle':'क्षेत्र मॉनिटर',
      'demoScenarios':    'डेमो परिदृश्य',
      'demoScenariosSub': 'यथार्थवादी फसल परिदृश्यों के बीच स्विच करें',
      'sensorData':       'रियल-टाइम सेंसर डेटा',
      'sensorCount':      '9 सेंसर',
      'smartRecs':        'स्मार्ट सुझाव',
      'activeAlerts':     'सक्रिय अलर्ट',
      'connecting':       'सेंसर से जुड़ रहा है...',
      'statusOptimal':    'इष्टतम',
      'statusCaution':    'सावधानी',
      'statusAlert':      'अलर्ट',
      'statusHealthy':    'स्वस्थ',
      'statusFair':       'ठीक',
      'statusPoor':       'खराब',
      'trendStable':      'स्थिर',
      'trendImproving':   'सुधर रहा है',
      'trendDeclining':   'घट रहा है',
    },

    // ── PUNJABI ──────────────────────────────────────────────────────────────
    'pa': {
      'appName':          'ਐਗਰੋਗਾਰਡ AI',
      'appBarTitle':      'ਐਗਰੋਗਾਰਡ AI  |  CoderPirates',
      'byCoderPirates':   'CoderPirates ਦੁਆਰਾ',
      'tagline':          'ਹਰ ਫਸਲ ਨੂੰ ਬੁੱਧੀਮਾਨੀ ਨਾਲ ਪੋਸ਼ਿਤ ਕਰਨਾ',
      'motto':            'ਖੇਤਾਂ ਦੀ ਰੱਖਿਆ, ਕਿਸਾਨਾਂ ਦਾ ਸਸ਼ਕਤੀਕਰਨ',
      'aiPowered':        'AI ਸੰਚਾਲਿਤ',
      'realTime':         'ਰੀਅਲ-ਟਾਈਮ',
      'organicTips':      'ਜੈਵਿਕ ਸੁਝਾਅ',
      'smartTools':       'ਸਮਾਰਟ ਟੂਲਸ',
      'features':         '5 ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
      'cropAdvisor':      'ਫਸਲ\nਸਲਾਹਕਾਰ',
      'cropAdvisorSub':   'AI ਸਿਫਾਰਿਸ਼ਾਂ',
      'diseaseDetector':  'ਰੋਗ\nਡਿਟੈਕਟਰ',
      'diseaseDetectorSub': 'ਪੱਤੀ ਚਿੱਤਰ ਵਿਸ਼ਲੇਸ਼ਣ',
      'fieldMonitor':     'ਖੇਤ\nਮਾਨੀਟਰ',
      'fieldMonitorSub':  'ਲਾਈਵ ਸੈਂਸਰ ਡੈਸ਼ਬੋਰਡ',
      'ecoGuardian':      'ਵਾਤਾਵਰਣ\nਰੱਖਿਅਕ',
      'ecoGuardianSub':   'ਸਥਿਰਤਾ ਸੂਝ',
      'aboutTitle':       'ਐਗਰੋਗਾਰਡ AI ਬਾਰੇ',
      'about1':           'ਮਿੱਟੀ ਅਤੇ ਮੌਸਮ ਦੇ ਆਧਾਰ \'ਤੇ ML ਸਿਫਾਰਿਸ਼ਾਂ',
      'about2':           'ਕੈਮਰੇ ਨਾਲ ਪੱਤੀ ਰੋਗ ਦੀ ਪਛਾਣ',
      'about3':           'ਰੀਅਲ-ਟਾਈਮ IoT ਸੈਂਸਰ ਨਿਗਰਾਨੀ',
      'about4':           'ਟਿਕਾਊ ਖੇਤੀ ਲਈ ਜੈਵਿਕ ਬਦਲ',
      'version':          'ਐਗਰੋਗਾਰਡ AI - CoderPirates v1.0.0',
      'copyright':        '© 2025 CoderPirates',
      'selectLanguage':   'ਭਾਸ਼ਾ ਚੁਣੋ',
      'language':         'ਭਾਸ਼ਾ',
      // Government Portal
      'govtServices':     'ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ',
      'govtServicesSub':  'ਮੰਡੀ ਭਾਅ, ਯੋਜਨਾਵਾਂ ਤੇ ਸਲਾਹ',
      'govtPortalTitle':  'ਸਰਕਾਰੀ ਸੇਵਾਵਾਂ',
      'govtPortalSubtitle':'ਮੰਡੀ ਭਾਅ, ਯੋਜਨਾਵਾਂ, ਬੀਮਾ ਤੇ ਸਲਾਹ ਵੇਖੋ',
      'govtPortalBadge':  'ਭਾਰਤ ਸਰਕਾਰ',
      'mandiPrices':      'ਮੰਡੀ ਭਾਅ',
      'mandiPricesSub':   'eNAM ਮੰਡੀਆਂ ਤੋਂ ਲਾਈਵ ਫ਼ਸਲ ਭਾਅ',
      'govtSchemes':      'ਸਰਕਾਰੀ ਯੋਜਨਾਵਾਂ',
      'govtSchemesSub':   '12+ ਯੋਜਨਾਵਾਂ ਵਿੱਚ ਯੋਗਤਾ ਜਾਂਚੋ',
      'cropInsurance':    'ਫ਼ਸਲ ਬੀਮਾ',
      'cropInsuranceSub': 'PMFBY ਪ੍ਰੀਮੀਅਮ ਕੈਲਕੁਲੇਟਰ ਤੇ ਦਾਅਵਾ ਟ੍ਰੈਕਰ',
      'govtAdvisories':   'ਸਰਕਾਰੀ ਸਲਾਹ',
      'govtAdvisoriesSub':'ਮੌਸਮ, ਕੀੜੇ ਤੇ ਫ਼ਸਲ ਪ੍ਰਬੰਧ ਅਲਰਟ',
      'govtDataNote':     'ਡੇਟਾ ਸਰੋਤ',
      'govtDataNoteDetail':'ਭਾਅ ਤੇ ਸਲਾਹ ਸਰਕਾਰੀ ਪੋਰਟਲ ਡੇਟਾ ਤੇ ਅਧਾਰਤ ਹਨ',
      'prices':           'ਭਾਅ',
      'schemes':          'ਯੋਜਨਾਵਾਂ',
      'alerts':           'ਅਲਰਟ',
      'critical':         'ਗੰਭੀਰ',
      'pricesAvailable':  'ਭਾਅ ਉਪਲਬਧ',
      'schemesAvailable': 'ਯੋਜਨਾਵਾਂ ਉਪਲਬਧ',
      'liveprices':       'ਲਾਈਵ ਭਾਅ',
      'marketAlerts':     'ਬਾਜ਼ਾਰ ਅਲਰਟ',
      'seasonalGuide':    'ਮੌਸਮੀ ਗਾਈਡ',
      'selectState':      'ਰਾਜ ਚੁਣੋ',
      'selectCrop':       'ਫ਼ਸਲ ਚੁਣੋ',
      'noData':           'ਕੋਈ ਡੇਟਾ ਨਹੀਂ',
      'noAlerts':         'ਕੋਈ ਅਲਰਟ ਨਹੀਂ',
      'priceOverview':    'ਭਾਅ ਸਮੀਖਿਆ',
      'avg':              'ਔਸਤ',
      'highest':          'ਵੱਧ',
      'lowest':           'ਘੱਟ',
      'aboveMSP':         'MSP ਤੋਂ ਉੱਪਰ',
      'belowMSP':         'MSP ਤੋਂ ਹੇਠਾਂ',
      'minPrice':         'ਘੱਟ',
      'modalPrice':       'ਮੋਡਲ',
      'maxPrice':         'ਵੱਧ',
      'arrival':          'ਆਮਦ',
      'bestSell':         'ਵੇਚਣ ਦਾ ਵਧੀਆ ਸਮਾਂ',
      'bestBuy':          'ਖ਼ਰੀਦਣ ਦਾ ਵਧੀਆ ਸਮਾਂ',
      'schemeCheckerTitle':'ਯੋਜਨਾ ਯੋਗਤਾ ਜਾਂਚ',
      'schemeCheckerSub': 'ਆਪਣੀ ਪ੍ਰੋਫ਼ਾਈਲ ਭਰੋ ਤੇ ਯੋਜਨਾਵਾਂ ਲੱਭੋ',
      'yourAge':          'ਤੁਹਾਡੀ ਉਮਰ',
      'enterAge':         'ਉਮਰ ਦਰਜ ਕਰੋ',
      'genderLabel':      'ਲਿੰਗ',
      'male':             'ਪੁਰਸ਼',
      'female':           'ਔਰਤ',
      'stateLabel':       'ਰਾਜ',
      'landHolding':      'ਜ਼ਮੀਨ (ਹੈਕਟੇਅਰ)',
      'enterLand':        'ਹੈਕਟੇਅਰ ਵਿੱਚ ਜ਼ਮੀਨ ਦਰਜ ਕਰੋ',
      'farmerTypeLabel':  'ਕਿਸਾਨ ਕਿਸਮ',
      'allTypes':         'ਸਾਰੀ ਕਿਸਮ',
      'smallMarginal':    'ਛੋਟੇ/ਸੀਮਾਂਤ',
      'mediumFarmer':     'ਦਰਮਿਆਨੇ',
      'largeFarmer':      'ਵੱਡੇ',
      'interestKeywords': 'ਦਿਲਚਸਪੀ ਸ਼ਬਦ (ਵਿਕਲਪਿਕ)',
      'enterKeywords':    'ਜਿਵੇਂ, ਸੋਲਰ, ਲੋਨ, ਜੈਵਿਕ',
      'checkEligibility': 'ਯੋਗਤਾ ਜਾਂਚੋ',
      'required':         'ਲੋੜੀਂਦਾ',
      'editProfile':      'ਪ੍ਰੋਫ਼ਾਈਲ ਬਦਲੋ',
      'youAreEligible':   'ਤੁਸੀਂ ਯੋਗ ਹੋ',
      'outOf':            'ਵਿੱਚੋਂ',
      'schemesWord':      'ਯੋਜਨਾਵਾਂ',
      'eligibilityNote':  'ਵੇਰਵੇ ਲਈ ਯੋਜਨਾ ਤੇ ਟੈਪ ਕਰੋ',
      'eligibleSchemes':  'ਯੋਗ ਯੋਜਨਾਵਾਂ',
      'notEligible':      'ਅਯੋਗ',
      'description':      'ਵੇਰਵਾ',
      'benefits':         'ਫ਼ਾਇਦੇ',
      'eligibilityReq':   'ਯੋਗਤਾ',
      'documents':        'ਲੋੜੀਂਦੇ ਦਸਤਾਵੇਜ਼',
      'howToApply':       'ਕਿਵੇਂ ਅਪਲਾਈ ਕਰੋ',
      'visitGovtPortal':  'ਸਰਕਾਰੀ ਪੋਰਟਲ ਦੇਖੋ',
      'govtPortalLinks':  'ਸਰਕਾਰੀ ਪੋਰਟਲ ਲਿਂਕ',
      'errorOccurred':    'ਗਲਤੀ ਹੋਈ',
      'calculator':       'ਕੈਲਕੁਲੇਟਰ',
      'claimStatus':      'ਦਾਅਵਾ ਸਥਿਤੀ',
      'deadlines':        'ਅੰਤਿਮ ਤਾਰੀਖ਼',
      'pmfbyCalc':        'PMFBY ਪ੍ਰੀਮੀਅਮ ਕੈਲਕੁਲੇਟਰ',
      'pmfbyCalcSub':     'ਫ਼ਸਲ ਬੀਮਾ ਪ੍ਰੀਮੀਅਮ ਕੈਲਕੁਲੇਟ ਕਰੋ',
      'selectSeason':     'ਮੌਸਮ ਚੁਣੋ',
      'areaHectares':     'ਖੇਤਰ (ਹੈਕਟੇਅਰ)',
      'calculatePremium': 'ਪ੍ਰੀਮੀਅਮ ਕੈਲਕੁਲੇਟ ਕਰੋ',
      'premiumBreakdown': 'ਪ੍ਰੀਮੀਅਮ ਵੇਰਵਾ',
      'crop':             'ਫ਼ਸਲ',
      'season':           'ਮੌਸਮ',
      'area':             'ਖੇਤਰ',
      'hectares':         'ਹੈਕਟੇਅਰ',
      'sumInsured':       'ਬੀਮਿਤ ਰਕਮ',
      'youPay':           'ਤੁਸੀਂ ਭੁਗਤਾਨ ਕਰੋ',
      'govtPays':         'ਸਰਕਾਰ ਭੁਗਤਾਨ ਕਰੇ',
      'govtSubsidy':      'ਸਰਕਾਰੀ ਸਬਸਿਡੀ',
      'enrollBy':         'ਨਾਮਾਂਕਨ ਤਾਰੀਖ਼',
      'applicationId':    'ਅਰਜ਼ੀ ਆਈਡੀ',
      'check':            'ਜਾਂਚੋ',
      'premiumPaid':      'ਪ੍ਰੀਮੀਅਮ ਭੁਗਤਾਨ',
      'insurer':          'ਬੀਮਾਕਰਤਾ',
      'claimAmount':      'ਦਾਅਵਾ ਰਕਮ',
      'timeline':         'ਸਮਾਂ-ਰੇਖਾ',
      'enrollStart':      'ਨਾਮਾਂਕਨ ਸ਼ੁਰੂ',
      'enrollEnd':        'ਨਾਮਾਂਕਨ ਅੰਤ',
      'seasonPeriod':     'ਮੌਸਮ ਅਵਧੀ',
      'allCategories':    'ਸਾਰੇ',
      'allStates':        'ਸਾਰੇ ਰਾਜ',
      'noAdvisories':     'ਕੋਈ ਸਲਾਹ ਨਹੀਂ ਮਿਲੀ',
      'cropAdvisorTitle': 'ਫਸਲ ਸਲਾਹਕਾਰ',
      'soilWeatherTitle': 'ਮਿੱਟੀ ਅਤੇ ਮੌਸਮ ਡੇਟਾ ਦਰਜ ਕਰੋ',
      'soilWeatherSub':   'ਸਾਡਾ AI ਤੁਹਾਡੇ ਖੇਤ ਦੀਆਂ ਸਥਿਤੀਆਂ ਦਾ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰਦਾ ਹੈ',
      'soilNutrients':    'ਮਿੱਟੀ ਪੋਸ਼ਕ ਤੱਤ',
      'weatherCond':      'ਮੌਸਮ ਅਤੇ ਮਿੱਟੀ ਦੀਆਂ ਸਥਿਤੀਆਂ',
      'nitrogen':         'ਨਾਈਟ੍ਰੋਜਨ (N)',
      'phosphorus':       'ਫਾਸਫੋਰਸ (P)',
      'potassium':        'ਪੋਟਾਸ਼ੀਅਮ (K)',
      'temperature':      'ਤਾਪਮਾਨ',
      'humidity':         'ਨਮੀ',
      'phLevel':          'pH ਪੱਧਰ',
      'rainfall':         'ਬਾਰਸ਼',
      'getRecommendation':'ਸਿਫਾਰਿਸ਼ ਪ੍ਰਾਪਤ ਕਰੋ',
      'analyzing':        'ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...',
      'recommendedCrop':  'ਸਿਫਾਰਿਸ਼ ਕੀਤੀ ਫਸਲ',
      'confidence':       'ਭਰੋਸਾ: ',
      'diseaseDetectorTitle': 'ਰੋਗ ਡਿਟੈਕਟਰ',
      'newAnalysis':      'ਨਵਾਂ ਵਿਸ਼ਲੇਸ਼ਣ',
      'history':          'ਇਤਿਹਾਸ',
      'uploadImage':      'ਪੱਤੀ / ਫਸਲ ਚਿੱਤਰ ਅਪਲੋਡ ਕਰੋ',
      'noImageSelected':  'ਕੋਈ ਚਿੱਤਰ ਨਹੀਂ ਚੁਣਿਆ',
      'takeOrChoose':     'ਫੋਟੋ ਲਓ ਜਾਂ ਗੈਲਰੀ ਤੋਂ ਚੁਣੋ',
      'gallery':          'ਗੈਲਰੀ',
      'camera':           'ਕੈਮਰਾ',
      'analyseDisease':   'ਰੋਗ ਲਈ ਵਿਸ਼ਲੇਸ਼ਣ ਕਰੋ',
      'analysing':        'ਵਿਸ਼ਲੇਸ਼ਣ ਹੋ ਰਿਹਾ ਹੈ...',
      'analysisResults':  'ਵਿਸ਼ਲੇਸ਼ਣ ਨਤੀਜੇ',
      'saveHistory':      'ਇਤਿਹਾਸ ਵਿੱਚ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'notesTitle':       'ਨੋਟਸ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'notesHint':        'ਉਦਾਹਰਨ: ਖੇਤ 3, ਦੱਖਣ ਕੋਨਾ...',
      'saveSuccess':      'ਵਿਸ਼ਲੇਸ਼ਣ ਸਫਲਤਾਪੂਰਵਕ ਸੁਰੱਖਿਅਤ!',
      'noHistoryYet':     'ਅਜੇ ਕੋਈ ਵਿਸ਼ਲੇਸ਼ਣ ਸੁਰੱਖਿਅਤ ਨਹੀਂ',
      'noHistoryHint':    'ਵਿਸ਼ਲੇਸ਼ਣ ਚਲਾਓ ਅਤੇ ਸੁਰੱਖਿਅਤ ਕਰੋ',
      'deleteAnalysis':   'ਵਿਸ਼ਲੇਸ਼ਣ ਮਿਟਾਓ',
      'deleteConfirm':    'ਇਸ ਰਿਕਾਰਡ ਨੂੰ ਸਥਾਈ ਤੌਰ \'ਤੇ ਮਿਟਾਓ?',
      'cancel':           'ਰੱਦ ਕਰੋ',
      'delete':           'ਮਿਟਾਓ',
      'symptoms':         'ਲੱਛਣ',
      'cause':            'ਕਾਰਨ',
      'treatment':        'ਇਲਾਜ',
      'prevention':       'ਰੋਕਥਾਮ',
      'organicOptions':   'ਜੈਵਿਕ / ਬਾਇਓ-ਕੰਟਰੋਲ ਵਿਕਲਪ',
      'preventiveCare':   'ਰੋਕਥਾਮੀ ਦੇਖਭਾਲ',
      'matchedDB':        'ਸਥਾਨਕ ਰੋਗ ਡੇਟਾਬੇਸ ਵਿੱਚ ਮਿਲਿਆ',
      'noDBMatch':        'ਕੋਈ ਸਥਾਨਕ DB ਮੇਲ ਨਹੀਂ',
      'totalAnalyses':    'ਕੁੱਲ',
      'avgConf':          'ਔਸਤ',
      'topDisease':       'ਮੁੱਖ ਰੋਗ',
      'fieldMonitorTitle':'ਖੇਤ ਮਾਨੀਟਰ',
      'demoScenarios':    'ਡੈਮੋ ਦ੍ਰਿਸ਼',
      'demoScenariosSub': 'ਯਥਾਰਥਵਾਦੀ ਫਸਲ ਦ੍ਰਿਸ਼ਾਂ ਵਿੱਚ ਬਦਲੋ',
      'sensorData':       'ਰੀਅਲ-ਟਾਈਮ ਸੈਂਸਰ ਡੇਟਾ',
      'sensorCount':      '9 ਸੈਂਸਰ',
      'smartRecs':        'ਸਮਾਰਟ ਸੁਝਾਅ',
      'activeAlerts':     'ਸਰਗਰਮ ਅਲਰਟ',
      'connecting':       'ਸੈਂਸਰਾਂ ਨਾਲ ਕਨੈਕਟ ਹੋ ਰਿਹਾ ਹੈ...',
      'statusOptimal':    'ਸਰਵੋਤਮ',
      'statusCaution':    'ਸਾਵਧਾਨੀ',
      'statusAlert':      'ਅਲਰਟ',
      'statusHealthy':    'ਸਿਹਤਮੰਦ',
      'statusFair':       'ਠੀਕ',
      'statusPoor':       'ਮਾੜਾ',
      'trendStable':      'ਸਥਿਰ',
      'trendImproving':   'ਸੁਧਰ ਰਿਹਾ ਹੈ',
      'trendDeclining':   'ਘੱਟ ਰਿਹਾ ਹੈ',
    },

    // ── TAMIL ────────────────────────────────────────────────────────────────
    'ta': {
      'appName':          'அக்ரோகார்ட் AI',
      'appBarTitle':      'அக்ரோகார்ட் AI  |  CoderPirates',
      'byCoderPirates':   'CoderPirates இன்',
      'tagline':          'ஒவ்வொரு அறுவடையையும் அறிவுடன் வளர்க்கிறோம்',
      'motto':            'விவசாயத்தை காக்கிறோம், விவசாயிகளை வலுப்படுத்துகிறோம்',
      'aiPowered':        'AI இயக்கம்',
      'realTime':         'நேரடி',
      'organicTips':      'இயற்கை குறிப்புகள்',
      'smartTools':       'ஸ்மார்ட் கருவிகள்',
      'features':         '5 அம்சங்கள்',
      'cropAdvisor':      'பயிர்\nஆலோசகர்',
      'cropAdvisorSub':   'AI பரிந்துரைகள்',
      'diseaseDetector':  'நோய்\nகண்டறிவி',
      'diseaseDetectorSub': 'இலை படம் பகுப்பாய்வு',
      'fieldMonitor':     'வயல்\nகண்காணிப்பு',
      'fieldMonitorSub':  'நேரடி சென்சார் டாஷ்போர்டு',
      'ecoGuardian':      'சுற்றுச்சூழல்\nகாவலர்',
      'ecoGuardianSub':   'நிலைத்தன்மை நுண்ணறிவு',
      'aboutTitle':       'AgroGuard AI பற்றி',
      'about1':           'மண் மற்றும் வானிலை அடிப்படையில் ML பரிந்துரைகள்',
      'about2':           'கேமரா மூலம் இலை நோய் கண்டறிதல்',
      'about3':           'நேரடி IoT சென்சார் கண்காணிப்பு',
      'about4':           'நிலையான விவசாயத்திற்கான இயற்கை மாற்றுகள்',
      'version':          'அக்ரோகார்ட் AI - CoderPirates v1.0.0',
      'copyright':        '© 2025 CoderPirates',
      'selectLanguage':   'மொழியை தேர்ந்தெடுக்கவும்',
      'language':         'மொழி',
      // Government Portal
      'govtServices':     'அரசு சேவைகள்',
      'govtServicesSub':  'சந்தை விலை, திட்டங்கள் மற்றும் ஆலோசனை',
      'govtPortalTitle':  'அரசு சேவைகள்',
      'govtPortalSubtitle':'சந்தை விலை, திட்டங்கள், காப்பீடு மற்றும் ஆலோசனை',
      'govtPortalBadge':  'இந்திய அரசு',
      'mandiPrices':      'சந்தை விலை',
      'mandiPricesSub':   'eNAM சந்தைகளில் நேரடி பயிர் விலை',
      'govtSchemes':      'அரசு திட்டங்கள்',
      'govtSchemesSub':   '12+ திட்டங்களில் தகுதி சோதிக்கவும்',
      'cropInsurance':    'பயிர் காப்பீடு',
      'cropInsuranceSub': 'PMFBY பிரீமியம் கணிப்பான் மற்றும் உரிமை கண்காணிப்பு',
      'govtAdvisories':   'அரசு ஆலோசனை',
      'govtAdvisoriesSub':'வானிலை, பூச்சி மற்றும் பயிர் மேலாண்மை எச்சரிக்கை',
      'govtDataNote':     'தரவு மூலம்',
      'govtDataNoteDetail':'விலைகள் மற்றும் ஆலோசனைகள் அரசு போர்ட்டல் தரவை அடிப்படையாகக் கொண்டவை',
      'prices':           'விலை',
      'schemes':          'திட்டங்கள்',
      'alerts':           'எச்சரிக்கை',
      'critical':         'முக்கியமான',
      'pricesAvailable':  'விலை கிடைக்கும்',
      'schemesAvailable': 'திட்டங்கள் கிடைக்கும்',
      'liveprices':       'நேரடி விலை',
      'marketAlerts':     'சந்தை எச்சரிக்கை',
      'seasonalGuide':    'பருவ வழிகாட்டி',
      'selectState':      'மாநிலத்தை தேர்ந்தெடுக்கவும்',
      'selectCrop':       'பயிரை தேர்ந்தெடுக்கவும்',
      'noData':           'தரவு இல்லை',
      'noAlerts':         'எச்சரிக்கை இல்லை',
      'priceOverview':    'விலை மேலோட்டம்',
      'avg':              'சராசரி',
      'highest':          'அதிகம்',
      'lowest':           'குறைவு',
      'aboveMSP':         'MSP மேலே',
      'belowMSP':         'MSP கீழே',
      'minPrice':         'குறைவு',
      'modalPrice':       'மாடல்',
      'maxPrice':         'அதிகம்',
      'arrival':          'வரவு',
      'bestSell':         'விற்க சிறந்த நேரம்',
      'bestBuy':          'வாங்க சிறந்த நேரம்',
      'schemeCheckerTitle':'திட்ட தகுதி சோதனை',
      'schemeCheckerSub': 'உங்கள் சுயவிவரத்தை நிரப்பி திட்டங்களைக் கண்டறியுங்கள்',
      'yourAge':          'உங்கள் வயது',
      'enterAge':         'வயதை உள்ளிடவும்',
      'genderLabel':      'பாலினம்',
      'male':             'ஆண்',
      'female':           'பெண்',
      'stateLabel':       'மாநிலம்',
      'landHolding':      'நிலம் (ஹெக்டேர்)',
      'enterLand':        'ஹெக்டேரில் நிலத்தை உள்ளிடவும்',
      'farmerTypeLabel':  'விவசாயி வகை',
      'allTypes':         'அனைத்து வகை',
      'smallMarginal':    'சிறு/குறு',
      'mediumFarmer':     'நடுத்தர',
      'largeFarmer':      'பெரிய',
      'interestKeywords': 'ஆர்வ சொற்கள் (விருப்பம்)',
      'enterKeywords':    'எ.கா., சோலார், கடன், இயற்கை',
      'checkEligibility': 'தகுதி சோதிக்கவும்',
      'required':         'அவசியம்',
      'editProfile':      'சுயவிவரம் மாற்றவும்',
      'youAreEligible':   'நீங்கள் தகுதியானவர்',
      'outOf':            'இல்',
      'schemesWord':      'திட்டங்கள்',
      'eligibilityNote':  'விவரங்களுக்கு திட்டத்தை தட்டவும்',
      'eligibleSchemes':  'தகுதியான திட்டங்கள்',
      'notEligible':      'தகுதியற்ற',
      'description':      'விவரம்',
      'benefits':         'பயன்கள்',
      'eligibilityReq':   'தகுதி',
      'documents':        'தேவையான ஆவணங்கள்',
      'howToApply':       'விண்ணப்பிக்கும் முறை',
      'visitGovtPortal':  'அரசு போர்ட்டலுக்குச் செல்க',
      'govtPortalLinks':  'அரசு போர்ட்டல் இணைப்புகள்',
      'errorOccurred':    'பிழை ஏற்பட்டது',
      'calculator':       'கணிப்பான்',
      'claimStatus':      'உரிமை நிலை',
      'deadlines':        'கடைசி தேதி',
      'pmfbyCalc':        'PMFBY பிரீமியம் கணிப்பான்',
      'pmfbyCalcSub':     'பயிர் காப்பீடு பிரீமியத்தை கணக்கிடுங்கள்',
      'selectSeason':     'பருவம் தேர்ந்தெடுக்கவும்',
      'areaHectares':     'பரப்பளவு (ஹெக்டேர்)',
      'calculatePremium': 'பிரீமியம் கணக்கிடுங்கள்',
      'premiumBreakdown': 'பிரீமியம் விவரம்',
      'crop':             'பயிர்',
      'season':           'பருவம்',
      'area':             'பரப்பளவு',
      'hectares':         'ஹெக்டேர்',
      'sumInsured':       'காப்பீடு தொகை',
      'youPay':           'நீங்கள் செலுத்துவது',
      'govtPays':         'அரசு செலுத்துவது',
      'govtSubsidy':      'அரசு மானியம்',
      'enrollBy':         'பதிவு தேதி',
      'applicationId':    'விண்ணப்ப எண்',
      'check':            'சோதிக்கவும்',
      'premiumPaid':      'பிரீமியம் செலுத்தியது',
      'insurer':          'காப்பீட்டாளர்',
      'claimAmount':      'உரிமை தொகை',
      'timeline':         'காலவரிசை',
      'enrollStart':      'பதிவு தொடக்கம்',
      'enrollEnd':        'பதிவு முடிவு',
      'seasonPeriod':     'பருவ காலம்',
      'allCategories':    'அனைத்தும்',
      'allStates':        'அனைத்து மாநிலங்கள்',
      'noAdvisories':     'ஆலோசனை எதுவும் இல்லை',
      'cropAdvisorTitle': 'பயிர் ஆலோசகர்',
      'soilWeatherTitle': 'மண் மற்றும் வானிலை தரவை உள்ளிடவும்',
      'soilWeatherSub':   'எங்கள் AI உங்கள் வயல் நிலைமைகளை பகுப்பாய்வு செய்கிறது',
      'soilNutrients':    'மண் ஊட்டச்சத்துக்கள்',
      'weatherCond':      'வானிலை மற்றும் மண் நிலைமைகள்',
      'nitrogen':         'நைட்ரஜன் (N)',
      'phosphorus':       'பாஸ்பரஸ் (P)',
      'potassium':        'பொட்டாசியம் (K)',
      'temperature':      'வெப்பநிலை',
      'humidity':         'ஈரப்பதம்',
      'phLevel':          'pH அளவு',
      'rainfall':         'மழைவீழ்ச்சி',
      'getRecommendation':'பரிந்துரை பெறுக',
      'analyzing':        'பகுப்பாய்வு நடக்கிறது...',
      'recommendedCrop':  'பரிந்துரைக்கப்பட்ட பயிர்',
      'confidence':       'நம்பகத்தன்மை: ',
      'diseaseDetectorTitle': 'நோய் கண்டறிவி',
      'newAnalysis':      'புதிய பகுப்பாய்வு',
      'history':          'வரலாறு',
      'uploadImage':      'இலை / பயிர் படம் பதிவேற்றவும்',
      'noImageSelected':  'படம் தேர்ந்தெடுக்கப்படவில்லை',
      'takeOrChoose':     'புகைப்படம் எடுக்கவும் அல்லது தேர்ந்தெடுக்கவும்',
      'gallery':          'கேலரி',
      'camera':           'கேமரா',
      'analyseDisease':   'நோய்க்காக பகுப்பாய்வு செய்',
      'analysing':        'பகுப்பாய்வு நடக்கிறது...',
      'analysisResults':  'பகுப்பாய்வு முடிவுகள்',
      'saveHistory':      'வரலாற்றில் சேமி',
      'notesTitle':       'குறிப்புகள் மற்றும் சேமி',
      'notesHint':        'எ.கா: வயல் 3, தெற்கு மூலை...',
      'saveSuccess':      'பகுப்பாய்வு வெற்றிகரமாக சேமிக்கப்பட்டது!',
      'noHistoryYet':     'இன்னும் பகுப்பாய்வு சேமிக்கப்படவில்லை',
      'noHistoryHint':    'பகுப்பாய்வு இயக்கி வரலாற்றில் சேமிக்கவும்',
      'deleteAnalysis':   'பகுப்பாய்வை நீக்கு',
      'deleteConfirm':    'இந்த பதிவை நிரந்தரமாக நீக்கவா?',
      'cancel':           'ரத்து செய்',
      'delete':           'நீக்கு',
      'symptoms':         'அறிகுறிகள்',
      'cause':            'காரணம்',
      'treatment':        'சிகிச்சை',
      'prevention':       'தடுப்பு',
      'organicOptions':   'இயற்கை / உயிரியல் கட்டுப்பாட்டு விருப்பங்கள்',
      'preventiveCare':   'தடுப்பு பராமரிப்பு',
      'matchedDB':        'உள்ளூர் நோய் தரவுத்தளத்தில் கண்டறியப்பட்டது',
      'noDBMatch':        'உள்ளூர் DB பொருத்தம் இல்லை',
      'totalAnalyses':    'மொத்தம்',
      'avgConf':          'சராசரி',
      'topDisease':       'முக்கிய நோய்',
      'fieldMonitorTitle':'வயல் கண்காணிப்பு',
      'demoScenarios':    'டெமோ காட்சிகள்',
      'demoScenariosSub': 'யதார்த்தமான பயிர் காட்சிகளுக்கு மாறவும்',
      'sensorData':       'நேரடி சென்சார் தரவு',
      'sensorCount':      '9 சென்சார்கள்',
      'smartRecs':        'ஸ்மார்ட் பரிந்துரைகள்',
      'activeAlerts':     'செயலில் உள்ள எச்சரிக்கைகள்',
      'connecting':       'சென்சார்களுடன் இணைக்கிறது...',
      'statusOptimal':    'உகந்தது',
      'statusCaution':    'எச்சரிக்கை',
      'statusAlert':      'அலர்ட்',
      'statusHealthy':    'ஆரோக்கியம்',
      'statusFair':       'நடுத்தரம்',
      'statusPoor':       'மோசம்',
      'trendStable':      'நிலையான',
      'trendImproving':   'மேம்படுகிறது',
      'trendDeclining':   'குறைகிறது',
    },

    // ── BENGALI ──────────────────────────────────────────────────────────────
    'bn': {
      'appName':          'অ্যাগ্রোগার্ড AI',
      'appBarTitle':      'অ্যাগ্রোগার্ড AI  |  CoderPirates',
      'byCoderPirates':   'CoderPirates দ্বারা',
      'tagline':          'প্রতিটি ফসল বুদ্ধিমত্তার সাথে লালন করা',
      'motto':            'খামার রক্ষা, কৃষক ক্ষমতায়ন',
      'aiPowered':        'AI চালিত',
      'realTime':         'রিয়েল-টাইম',
      'organicTips':      'জৈব টিপস',
      'smartTools':       'স্মার্ট টুলস',
      'features':         '৫ বৈশিষ্ট্য',
      'cropAdvisor':      'ফসল\nউপদেষ্টা',
      'cropAdvisorSub':   'AI পরিচালিত সুপারিশ',
      'diseaseDetector':  'রোগ\nসনাক্তকারী',
      'diseaseDetectorSub': 'পাতার ছবি বিশ্লেষণ',
      'fieldMonitor':     'মাঠ\nমনিটর',
      'fieldMonitorSub':  'লাইভ সেন্সর ড্যাশবোর্ড',
      'ecoGuardian':      'পরিবেশ\nরক্ষক',
      'ecoGuardianSub':   'টেকসই অন্তর্দৃষ্টি',
      'aboutTitle':       'AgroGuard AI সম্পর্কে',
      'about1':           'মাটি ও আবহাওয়ার উপর ভিত্তি করে ML ফসল সুপারিশ',
      'about2':           'ক্যামেরা-ভিত্তিক পাতার রোগ সনাক্তকরণ',
      'about3':           'রিয়েল-টাইম IoT সেন্সর পর্যবেক্ষণ',
      'about4':           'টেকসই চাষের জন্য জৈব বিকল্প',
      'version':          'অ্যাগ্রোগার্ড AI - CoderPirates v1.0.0',
      'copyright':        '© 2025 CoderPirates',
      'selectLanguage':   'ভাষা নির্বাচন করুন',
      'language':         'ভাষা',
      // Government Portal
      'govtServices':     'সরকারি সেবা',
      'govtServicesSub':  'মান্ডি দাম, প্রকল্প ও পরামর্শ',
      'govtPortalTitle':  'সরকারি সেবা',
      'govtPortalSubtitle':'মান্ডি দাম, প্রকল্প, বীমা ও পরামর্শ দেখুন',
      'govtPortalBadge':  'ভারত সরকার',
      'mandiPrices':      'মান্ডি দাম',
      'mandiPricesSub':   'eNAM মান্ডি থেকে সরাসরি ফসলের দাম',
      'govtSchemes':      'সরকারি প্রকল্প',
      'govtSchemesSub':   '12+ প্রকল্পে যোগ্যতা যাচাই করুন',
      'cropInsurance':    'ফসল বীমা',
      'cropInsuranceSub': 'PMFBY প্রিমিয়াম ক্যালকুলেটর ও দাবি ট্র্যাকার',
      'govtAdvisories':   'সরকারি পরামর্শ',
      'govtAdvisoriesSub':'আবহাওয়া, পোকা ও ফসল ব্যবস্থাপনা সতর্কতা',
      'govtDataNote':     'ডেটা উৎস',
      'govtDataNoteDetail':'দাম ও পরামর্শ সরকারি পোর্টাল ডেটার ওপর ভিত্তি করে',
      'prices':           'দাম',
      'schemes':          'প্রকল্প',
      'alerts':           'সতর্কতা',
      'critical':         'গুরুতর',
      'pricesAvailable':  'দাম উপলব্ধ',
      'schemesAvailable': 'প্রকল্প উপলব্ধ',
      'liveprices':       'সরাসরি দাম',
      'marketAlerts':     'বাজার সতর্কতা',
      'seasonalGuide':    'মৌসুমী গাইড',
      'selectState':      'রাজ্য নির্বাচন করুন',
      'selectCrop':       'ফসল নির্বাচন করুন',
      'noData':           'কোনো ডেটা নেই',
      'noAlerts':         'কোনো সতর্কতা নেই',
      'priceOverview':    'দাম পর্যালোচনা',
      'avg':              'গড়',
      'highest':          'সর্বোচ্চ',
      'lowest':           'সর্বনিম্ন',
      'aboveMSP':         'MSP থেকে বেশি',
      'belowMSP':         'MSP থেকে কম',
      'minPrice':         'সর্বনিম্ন',
      'modalPrice':       'মডেল',
      'maxPrice':         'সর্বোচ্চ',
      'arrival':          'আগমন',
      'bestSell':         'বিক্রির সেরা সময়',
      'bestBuy':          'কেনার সেরা সময়',
      'schemeCheckerTitle':'প্রকল্প যোগ্যতা যাচাই',
      'schemeCheckerSub': 'আপনার প্রোফাইল পূরণ করুন ও প্রকল্প খুঁজুন',
      'yourAge':          'আপনার বয়স',
      'enterAge':         'বয়স লিখুন',
      'genderLabel':      'লিঙ্গ',
      'male':             'পুরুষ',
      'female':           'মহিলা',
      'stateLabel':       'রাজ্য',
      'landHolding':      'জমি (হেক্টর)',
      'enterLand':        'হেক্টরে জমি লিখুন',
      'farmerTypeLabel':  'কৃষক ধরন',
      'allTypes':         'সব ধরন',
      'smallMarginal':    'ক্ষুদ্র/প্রান্তিক',
      'mediumFarmer':     'মাঝারি',
      'largeFarmer':      'বড়',
      'interestKeywords': 'আগ্রহের শব্দ (ঐচ্ছিক)',
      'enterKeywords':    'যেমন, সোলার, ঋণ, জৈব',
      'checkEligibility': 'যোগ্যতা যাচাই করুন',
      'required':         'আবশ্যক',
      'editProfile':      'প্রোফাইল পরিবর্তন',
      'youAreEligible':   'আপনি যোগ্য',
      'outOf':            'এর মধ্যে',
      'schemesWord':      'প্রকল্প',
      'eligibilityNote':  'বিস্তারিত দেখতে প্রকল্পে ট্যাপ করুন',
      'eligibleSchemes':  'যোগ্য প্রকল্প',
      'notEligible':      'অযোগ্য',
      'description':      'বিবরণ',
      'benefits':         'সুবিধা',
      'eligibilityReq':   'যোগ্যতা',
      'documents':        'প্রয়োজনীয় নথি',
      'howToApply':       'কীভাবে আবেদন করবেন',
      'visitGovtPortal':  'সরকারি পোর্টালে যান',
      'govtPortalLinks':  'সরকারি পোর্টাল লিঙ্ক',
      'errorOccurred':    'ত্রুটি হয়েছে',
      'calculator':       'ক্যালকুলেটর',
      'claimStatus':      'দাবি অবস্থা',
      'deadlines':        'শেষ তারিখ',
      'pmfbyCalc':        'PMFBY প্রিমিয়াম ক্যালকুলেটর',
      'pmfbyCalcSub':     'ফসল বীমা প্রিমিয়াম হিসাব করুন',
      'selectSeason':     'মৌসুম নির্বাচন করুন',
      'areaHectares':     'এলাকা (হেক্টর)',
      'calculatePremium': 'প্রিমিয়াম হিসাব করুন',
      'premiumBreakdown': 'প্রিমিয়াম বিবরণ',
      'crop':             'ফসল',
      'season':           'মৌসুম',
      'area':             'এলাকা',
      'hectares':         'হেক্টর',
      'sumInsured':       'বীমাকৃত অর্থ',
      'youPay':           'আপনি দেন',
      'govtPays':         'সরকার দেয়',
      'govtSubsidy':      'সরকারি ভর্তুকি',
      'enrollBy':         'তালিকাভুক্তি তারিখ',
      'applicationId':    'আবেদন আইডি',
      'check':            'যাচাই',
      'premiumPaid':      'প্রিমিয়াম পরিশোধ',
      'insurer':          'বীমাকারী',
      'claimAmount':      'দাবি অর্থ',
      'timeline':         'সময়রেখা',
      'enrollStart':      'তালিকাভুক্তি শুরু',
      'enrollEnd':        'তালিকাভুক্তি শেষ',
      'seasonPeriod':     'মৌসুম সময়কাল',
      'allCategories':    'সব',
      'allStates':        'সব রাজ্য',
      'noAdvisories':     'কোনো পরামর্শ পাওয়া যায়নি',
      'cropAdvisorTitle': 'ফসল উপদেষ্টা',
      'soilWeatherTitle': 'মাটি ও আবহাওয়ার তথ্য দিন',
      'soilWeatherSub':   'আমাদের AI আপনার জমির অবস্থা বিশ্লেষণ করে সেরা ফসলের সুপারিশ করে',
      'soilNutrients':    'মাটির পুষ্টি উপাদান',
      'weatherCond':      'আবহাওয়া ও মাটির অবস্থা',
      'nitrogen':         'নাইট্রোজেন (N)',
      'phosphorus':       'ফসফরাস (P)',
      'potassium':        'পটাসিয়াম (K)',
      'temperature':      'তাপমাত্রা',
      'humidity':         'আর্দ্রতা',
      'phLevel':          'pH মাত্রা',
      'rainfall':         'বৃষ্টিপাত',
      'getRecommendation':'সুপারিশ পান',
      'analyzing':        'বিশ্লেষণ হচ্ছে...',
      'recommendedCrop':  'প্রস্তাবিত ফসল',
      'confidence':       'নিশ্চিততা: ',
      'diseaseDetectorTitle': 'রোগ সনাক্তকারী',
      'newAnalysis':      'নতুন বিশ্লেষণ',
      'history':          'ইতিহাস',
      'uploadImage':      'পাতা / ফসলের ছবি আপলোড করুন',
      'noImageSelected':  'কোনো ছবি নির্বাচন করা হয়নি',
      'takeOrChoose':     'ছবি তুলুন বা গ্যালারি থেকে চয়ন করুন',
      'gallery':          'গ্যালারি',
      'camera':           'ক্যামেরা',
      'analyseDisease':   'রোগের জন্য বিশ্লেষণ করুন',
      'analysing':        'বিশ্লেষণ হচ্ছে...',
      'analysisResults':  'বিশ্লেষণ ফলাফল',
      'saveHistory':      'ইতিহাসে সংরক্ষণ করুন',
      'notesTitle':       'নোট ও সংরক্ষণ',
      'notesHint':        'যেমন: মাঠ ৩, দক্ষিণ কোণ...',
      'saveSuccess':      'বিশ্লেষণ সফলভাবে সংরক্ষিত!',
      'noHistoryYet':     'এখনো কোনো বিশ্লেষণ সংরক্ষিত হয়নি',
      'noHistoryHint':    'বিশ্লেষণ চালান এবং ইতিহাসে সংরক্ষণ করুন',
      'deleteAnalysis':   'বিশ্লেষণ মুছুন',
      'deleteConfirm':    'এই রেকর্ডটি স্থায়ীভাবে মুছে দেবেন?',
      'cancel':           'বাতিল',
      'delete':           'মুছুন',
      'symptoms':         'উপসর্গ',
      'cause':            'কারণ',
      'treatment':        'চিকিৎসা',
      'prevention':       'প্রতিরোধ',
      'organicOptions':   'জৈব / জৈব-নিয়ন্ত্রণ বিকল্প',
      'preventiveCare':   'প্রতিরোধমূলক যত্ন',
      'matchedDB':        'স্থানীয় রোগ ডেটাবেজে পাওয়া গেছে',
      'noDBMatch':        'কোনো স্থানীয় DB মিল নেই',
      'totalAnalyses':    'মোট',
      'avgConf':          'গড়',
      'topDisease':       'প্রধান রোগ',
      'fieldMonitorTitle':'মাঠ মনিটর',
      'demoScenarios':    'ডেমো পরিস্থিতি',
      'demoScenariosSub': 'বাস্তবসম্মত ফসল পরিস্থিতির মধ্যে পরিবর্তন করুন',
      'sensorData':       'রিয়েল-টাইম সেন্সর ডেটা',
      'sensorCount':      '৯ সেন্সর',
      'smartRecs':        'স্মার্ট সুপারিশ',
      'activeAlerts':     'সক্রিয় সতর্কতা',
      'connecting':       'সেন্সরগুলির সাথে সংযোগ হচ্ছে...',
      'statusOptimal':    'সঠিক',
      'statusCaution':    'সতর্কতা',
      'statusAlert':      'সতর্কবার্তা',
      'statusHealthy':    'সুস্থ',
      'statusFair':       'মধ্যম',
      'statusPoor':       'দুর্বল',
      'trendStable':      'স্থিতিশীল',
      'trendImproving':   'উন্নতি হচ্ছে',
      'trendDeclining':   'হ্রাস পাচ্ছে',
    },
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Language Picker Bottom Sheet – reusable across the app
// ─────────────────────────────────────────────────────────────────────────────

void showLanguagePicker(BuildContext context) {
  showModalBottomSheet(
    context: context,
    backgroundColor: Colors.transparent,
    isScrollControlled: true,
    builder: (_) => const _LanguagePickerSheet(),
  );
}

class _LanguagePickerSheet extends StatefulWidget {
  const _LanguagePickerSheet();

  @override
  State<_LanguagePickerSheet> createState() => _LanguagePickerSheetState();
}

class _LanguagePickerSheetState extends State<_LanguagePickerSheet>
    with SingleTickerProviderStateMixin {
  late AnimationController _ac;
  late Animation<double> _slideUp;

  @override
  void initState() {
    super.initState();
    _ac = AnimationController(vsync: this, duration: const Duration(milliseconds: 320));
    _slideUp = CurvedAnimation(parent: _ac, curve: Curves.easeOutCubic);
    _ac.forward();
  }

  @override
  void dispose() {
    _ac.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: _slideUp,
      builder: (_, child) => SlideTransition(
        position: Tween<Offset>(begin: const Offset(0, 1), end: Offset.zero)
            .animate(_slideUp),
        child: child,
      ),
      child: Container(
        decoration: const BoxDecoration(
          color: Color(0xFFFAFAF5),
          borderRadius: BorderRadius.vertical(top: Radius.circular(24)),
        ),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            // Drag handle
            Container(
              width: 40, height: 4,
              margin: const EdgeInsets.only(top: 12, bottom: 4),
              decoration: BoxDecoration(
                color: Colors.grey.shade300,
                borderRadius: BorderRadius.circular(2),
              ),
            ),

            // Header
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 20, vertical: 14),
              child: Row(
                children: [
                  Container(
                    padding: const EdgeInsets.all(8),
                    decoration: BoxDecoration(
                      color: const Color(0xFF2D6A4F).withValues(alpha: 0.1),
                      borderRadius: BorderRadius.circular(10),
                    ),
                    child: const Icon(Icons.translate_rounded,
                        color: Color(0xFF2D6A4F), size: 20),
                  ),
                  const SizedBox(width: 12),
                  Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      Text(
                        AppStrings.t('selectLanguage'),
                        style: const TextStyle(
                          fontSize: 17, fontWeight: FontWeight.w700,
                          color: Color(0xFF1B2A1B),
                        ),
                      ),
                      Text(
                        'Choose your preferred language',
                        style: TextStyle(fontSize: 12, color: Colors.grey.shade500),
                      ),
                    ],
                  ),
                ],
              ),
            ),

            const Divider(height: 1, color: Color(0xFFE8E8E8)),

            // Language list
            ValueListenableBuilder<String>(
              valueListenable: AppLang.current,
              builder: (_, selected, __) => ConstrainedBox(
                constraints: BoxConstraints(
                  maxHeight: MediaQuery.of(context).size.height * 0.55,
                ),
                child: SingleChildScrollView(
                  padding: const EdgeInsets.fromLTRB(16, 12, 16, 24),
                  child: Column(
                    children: AppLang.languages.map((lang) {
                    final isSelected = selected == lang['code'];
                    return GestureDetector(
                      onTap: () {
                        AppLang.current.value = lang['code']!;
                        Navigator.pop(context);
                      },
                      child: AnimatedContainer(
                        duration: const Duration(milliseconds: 200),
                        margin: const EdgeInsets.only(bottom: 10),
                        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 14),
                        decoration: BoxDecoration(
                          color: isSelected
                              ? const Color(0xFF2D6A4F)
                              : Colors.white,
                          borderRadius: BorderRadius.circular(14),
                          border: Border.all(
                            color: isSelected
                                ? const Color(0xFF2D6A4F)
                                : const Color(0xFFE0E0E0),
                            width: isSelected ? 2 : 1,
                          ),
                          boxShadow: isSelected
                              ? [BoxShadow(
                                  color: const Color(0xFF2D6A4F).withValues(alpha: 0.25),
                                  blurRadius: 10, offset: const Offset(0, 4))]
                              : [],
                        ),
                        child: Row(
                          children: [
                            // Flag + native name
                            Text(lang['flag']!, style: const TextStyle(fontSize: 26)),
                            const SizedBox(width: 14),
                            Expanded(
                              child: Column(
                                crossAxisAlignment: CrossAxisAlignment.start,
                                children: [
                                  Text(
                                    lang['native']!,
                                    style: TextStyle(
                                      fontSize: 15, fontWeight: FontWeight.w700,
                                      color: isSelected ? Colors.white : const Color(0xFF1B2A1B),
                                    ),
                                  ),
                                  Text(
                                    lang['name']!,
                                    style: TextStyle(
                                      fontSize: 12,
                                      color: isSelected
                                          ? Colors.white.withValues(alpha: 0.75)
                                          : Colors.grey.shade500,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                            if (isSelected)
                              const Icon(Icons.check_circle_rounded,
                                  color: Colors.white, size: 22),
                          ],
                        ),
                      ),
                    );
                  }).toList(),
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
